<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Language strings for originality report (English)
 *
 * @package    report_originality
 * @copyright  2025 Mattan Dor (CentricApp)
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

$string['pluginname'] = 'Originality Reports';
$string['originality:view'] = 'View originality reports';
$string['filters'] = 'Filters';
$string['graderange'] = 'Grade range';
$string['mingrade'] = 'Min grade';
$string['maxgrade'] = 'Max grade';
$string['startdate'] = 'Start date';
$string['enddate'] = 'End date';
$string['applyfilters'] = 'Apply filters';
$string['resetfilters'] = 'Reset filters';
$string['coursename'] = 'Course name';
$string['enrolledstudents'] = 'Enrolled students';
$string['averagegrade'] = 'Grade';
$string['completionrate'] = 'Completion rate';
$string['nocoursesfound'] = 'No courses found matching the criteria';
$string['invalidmingrade'] = 'Minimum grade must be between 0 and 100';
$string['invalidmaxgrade'] = 'Maximum grade must be between 0 and 100';
$string['invalidgraderange'] = 'Minimum grade must be less than maximum grade';
$string['invaliddaterange'] = 'Start date must be before end date';

// Report type strings
$string['reporttype'] = 'Report Type';
$string['teachers_no_reports'] = 'Teachers who haven\'t opened reports';
$string['lowest_grade_courses'] = 'Courses with lowest average grade';
$string['lowest_grade_students'] = 'Students with lowest average grade';
$string['submission_count'] = 'Assignments submitted';
$string['average_originality_score'] = 'Average originality score';

// Additional strings
$string['department'] = 'Department';
$string['lastaccess'] = 'Date';
$string['never'] = 'Never';
$string['email'] = 'Email';
$string['coursescount'] = 'Courses';
$string['details'] = 'Details';
$string['originality_score'] = 'Originality score';
$string['submissions'] = 'Submissions';
$string['modulename'] = 'Module name';

// Add a string for overall average
$string['overall_average'] = 'Overall average';

// PDF Export
$string['exportpdf'] = 'Export to PDF';
$string['exportcsv'] = 'Export to CSV';
$string['exportreport'] = 'Export Report';
$string['pdfreporttitle'] = 'Originality Report';
$string['pdfreportsubtitle'] = 'Generated on {$a}';
$string['pdfreportfilters'] = 'Filters applied:';
$string['pdfreportfiltergrade'] = 'Grade range: {$a->min} - {$a->max}';
$string['pdfreportfilterdate'] = 'Date range: {$a->start} - {$a->end}';

// Settings
$string['settings'] = 'Report Settings';
$string['logo'] = 'Report Logo';
$string['logodesc'] = 'Upload a logo to be displayed in the header of PDF reports. Recommended size: 300x100px.';
$string['footertext'] = 'Report Footer Text';
$string['footertextdesc'] = 'Enter the text to be displayed in the footer of PDF reports.';
$string['defaultfooter'] = 'Generated by Originality Reports Plugin for Moodle';
